### ISSUE TITLE
Wrong index of list item

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/previewer#43]
Check this post https://khala.subsquare.io/treasury/proposal/15 .

Editor content:
![u4orEoNLXz](https://user-images.githubusercontent.com/2264908/179765508-c4c46bd0-ad93-4865-b115-90285728fdd7.jpg)

The preview effect:
![usO6mkYsNh](https://user-images.githubusercontent.com/2264908/179765519-d5a9e8a4-d897-42d5-b1b2-ee28213a1ffd.jpg)

**Comment by 2nthony** [comment]
Not this business, https://github.com/opensquare-network/subsquare/issues/1772
